version: '3.4'

networks:
  frontend:
  backend:

services:
  event:
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    image: events/eventapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventDb
      DatabaseUser: sa
      DatabaseUserPassword: EventApi(!)
      ExternalEventBaseUrl: http://localhost:5060
    ports:
      - "5060:80"
    container_name: eventapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: events/cartapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.1.22:5015
      ConnectionString: basket.data
    ports:
      - "5005:80"
    container_name: cartapi
    networks:
      - backend
      - frontend
    depends_on:
      - basket.data
      - tokenserver
      - rabbitmq

  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: events/orderapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.1.22:5015
      SQLSERVER_HOST: eventdb
      SA_PASSWORD: EventApi(!)
      DATABASE: OrdersDb
    ports:
      - "5065:80"
    container_name: orderapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver
      - tokenserver
      - rabbitmq
   
      

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:5045
    ports:
      - "5015:80"
    container_name: tokenserviceapi1
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  webmvc:
    build:
      context: .\webmvc
      dockerfile: Dockerfile
    image: events/webmvc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    container_name: webshop1
    environment:
      EventUrl: http://event
      IdentityUrl: http://192.168.1.22:5015
      CallBackUrl: http://localhost:5045
      CartUrl: http://cart
      OrderUrl: http://order
      StripePublicKey: pk_test_GJtMaolsgxI5jQtkuq8rDdjD00qbRyn2e8
      StripePrivateKey: sk_test_NVXfiXyRDmTZVge5c3Zza7Fe00cHgjPL9M
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5045:80"
    networks:
      - frontend
    depends_on:
      - event
      - tokenserver
      - cart
      - order


  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    container_name: eventdb
    ports:
      - "1448:1433"
    networks:
      - backend

  basket.data:
    image: redis
    ports:
      - "6378:6379"  
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: myrabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    volumes:
      - ~/rabbitmq:/var/lib/rabbitmq/mnesia   
    networks:
      - backend 